[project]
name = "task_manager"
version = "0.1.0"
description = "Task manager. Hexlet project 4"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "gunicorn>=23.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
