# Generated by Django 5.2 on 2025-06-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_label_status_task_tasklabel_delete_labels_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_assigned', to='users.userproxy'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to='users.userproxy'),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, through='tasks.TaskLabel', to='tasks.label'),
        ),
    ]
