# Generated by Django 5.2 on 2025-06-05 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_assigned_to_alter_task_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.label'),
        ),
    ]
