name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Run linter and pytest
        env:
            DATABASE_URL: "sqlite:///:memory"
            SECRET_KEY: "any_key"
        run: |
          make check
      - name: Run test coverage
        env:
            DATABASE_URL: "sqlite:///:memory"
            SECRET_KEY: "any_key"
        run: |
          make test-coverage

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=coder108-gh_python-project-52
            -Dsonar.organization=coder108-gh
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**


